packages:
  - "apps/*"
  - "packages/*"

supportedArchitectures:
  os:
    - linux
  cpu:
    - x64
  libc:
    - glibc

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - bcrypt
  - esbuild
  - prisma
  - sharp
