packages:
  - "apps/*"
  - "packages/*"

supportedArchitectures:
  os:
    - linux
  cpu:
    - x64
  libc:
    - glibc

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  bcrypt: set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
